[feat] flakify
MrcJkb/haskell-tools.nvim pull request #59
Opened 2022-11-17 00:18 UTC by MangoIV

###### Description of changes

###### Things done

- [x] Tested, as applicable:
  - [x] Manually
- [x] Updated [CHANGELOG.md](../CHANGELOG.md) (if applicable).
- [x] Fits [CONTRIBUTING.md](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/CONTRIBUTING.md)

This is still in draft format as I want to add something more so one can properly use that within their system configuration.

2022-11-17 23:15 UTC, MangoIV commented
For some reason I cannot get it to work, it's not the fault of this nix code, though, as I also cannot get it to work with the nixpkgs version; for some reason I get undefined token repl when trying to use the repl options and the lsp doesn't register; i.e. all of the language servers show up but the haskell one. What could be ther reason?

2022-11-17 23:49 UTC, MrcJkb commented
Thanks so much for this! Now I finally know how to use GitHub actions with flakes :tada:

2022-11-17 23:50 UTC, MrcJkb requested changes
Just some minor nitpicks...

2022-11-17 23:50 UTC, MrcJkb commented on CHANGELOG.md
> +- flake setup
```suggestion
- Nix flake setup
```

2022-11-17 23:50 UTC, MrcJkb commented on README.md
> +home-manager configuration.
```suggestion
For NixOS users with flakes enabled, this project provides outputs in the form of a package and an overlay; use it as you wish in your nixos or home-manager configuration.
It is also available on `nixpkgs`.
```

2022-11-17 23:53 UTC, MrcJkb approved these changes

2022-11-17 23:53 UTC, merged

2022-11-18 00:18 UTC, MangoIV commented
Thank you!